version: '3.7'

services:
##################################################
# Reservation Manager Microservice + Dapr sidecars
##################################################
  reservation-manager:
    image: ${DOCKER_REGISTRY-}sagawayreservationdemoreservationmanager
    build:
      context: .
      dockerfile: Sagaway.ReservationDemo/Sagaway.ReservationDemo.ReservationManager/Dockerfile
    ports:
      - "4545:80"
    networks:
      - sagaway-network
    environment:
      - ACTOR_TYPE=CarReservationActor
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://reservation-manager:80
    depends_on:
      - rabbitmq
      - redis
      - zipkin
      - placement

  reservation-manager-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
     "-app-id", "reservation-manager",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/config.yaml"]
    volumes:
        - "./dapr/:/dapr"
    depends_on:
      - reservation-manager
    network_mode: "service:reservation-manager"
    

##################################################
# Billing Manager Microservice + Dapr sidecars
##################################################
  billing-management:
    image: ${DOCKER_REGISTRY-}sagawayreservationdemobillingmanagement
    build:
      context: .
      dockerfile: Sagaway.ReservationDemo/Sagaway.ReservationDemo.BillingManagment/Dockerfile
    depends_on:
      - rabbitmq
      - redis
      - zipkin
    networks:
      - sagaway-network
    environment:
    # - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://billing-management:80

  billing-management-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
     "-app-id", "billing-management",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/config.yaml"]
    volumes:
        - "./dapr/:/dapr"
    depends_on:
      - billing-management
    network_mode: "service:billing-management"

##################################################
# Inventory Manager Microservice + Dapr sidecars
##################################################
  inventory-management:
    image: ${DOCKER_REGISTRY-}sagawayreservationdemoinventorymanagement
    build:
      context: .
      dockerfile: Sagaway.ReservationDemo/Sagaway.ReservationDemo.InventoryManagement/Dockerfile
    depends_on:
      - rabbitmq
      - redis
      - zipkin
    networks:
      - sagaway-network
    environment:
    # - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://inventory-management:80

  inventory-management-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
     "-app-id", "inventory-management",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/config.yaml"]
    volumes:
        - "./dapr/:/dapr"
    depends_on:
      - inventory-management
    network_mode: "service:inventory-management"

##################################################
# Booking Manager Microservice + Dapr sidecars
##################################################
  booking-management:
    image: ${DOCKER_REGISTRY-}sagawayreservationdemobookingmanagement
    build:
      context: .
      dockerfile: Sagaway.ReservationDemo/Sagaway.ReservationDemo.BookingManagement/Dockerfile
    depends_on:
      - rabbitmq
      - redis
      - zipkin
    networks:
      - sagaway-network
    environment:
    # - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://booking-management:80

  booking-management-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
     "-app-id", "booking-management",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/config.yaml"]
    volumes:
        - "./dapr/:/dapr"
    depends_on:
      - booking-management
    network_mode: "service:booking-management"

############################
# Test Services
############################

### Orchestration Service ###
  orchestrationservice:
    image: ${DOCKER_REGISTRY-}sagawayintegrationtestsorchestrationservice
    build:
      context: .
      dockerfile: Sagaway.IntegrationTests/Sagaway.IntegrationTests.OrchestrationService/Dockerfile
    networks:
      - sagaway-network
    ports:
      - "6969:80"
    environment:
      - ACTOR_TYPE=TestActor
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://orchestrationservice:80
    depends_on:
      - rabbitmq
      - redis
      - zipkin
      - placement

  orchestrationservice-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
     "-app-id", "orchestrationservice",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/config.yaml"]
    volumes:
        - "./dapr/:/dapr"
    depends_on:
      - orchestrationservice
    network_mode: "service:orchestrationservice"

## Test Service ##
  testservice:
    image: ${DOCKER_REGISTRY-}sagawayintegrationteststestservice
    build:
      context: .
      dockerfile: Sagaway.IntegrationTests/Sagaway.IntegrationTests.TestService/Dockerfile
    networks:
      - sagaway-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://testservice:80
    depends_on:
      - rabbitmq
      - redis
      - zipkin
      - placement

  testservice-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
     "-app-id", "testservice",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/config.yaml"]
    volumes:
        - "./dapr/:/dapr"
    depends_on:
      - testservice
    network_mode: "service:testservice"


############################
# RabitMQ
############################
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sagaway-network

############################
# Redis state store
############################
  redis:
    image: "redis:alpine"
    hostname: redisserver
    ports:
      - "6379:6379"
    networks:
      - sagaway-network
    command: redis-server 
    environment:
     - REDIS_REPLICATION_MODE=master
 
#############################
## Dapr placement service
#############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - sagaway-network
 
############################
# Dapr zipkin service
############################
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    networks:
      - sagaway-network
 
#############################
## Dapr Dashboard
#############################
  dapr-dashboard:
    image: daprio/dashboard:latest
    container_name: dashboard
    ports:
      - "8080:8080"
    volumes:
      - "./dapr/:/home/nonroot/.dapr"
    networks:
      - sagaway-network
 
############################
# SignalR emulator service
############################
  signalr:
    image: ${DOCKER_REGISTRY-}signalremulator
    build:
      context: .
      dockerfile: ./SignalREmulator/Dockerfile
    ports:
      - 8888:8888
      - 7071:7071
    volumes:
     - ./workspace:/workspace
    environment:
      - ASRS_EMULATOR_PORT=8888
#      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8888;http://+:7071

############################
# Global settings
############################
 
networks:
  sagaway-network:
           
volumes: 
  workspace:  




