version: '3.7'

services:
############################
# Test Services
############################

### Orchestration Service ###
  orchestrationservice:
    environment:
      - AZURE__SignalR__ConnectionString=${SignalRConnectionString}
  

 