apiVersion: v1
kind: Secret
metadata:
  name: dapr-secrets
type: Opaque
stringData:
  SignalRConnectionString: "Endpoint=http://signalr:8888;Port=8888;AccessKey=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGH;Version=1.0;"