apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: sagaway
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: queryIndexes
    value: |
      [
        {
          "name": "customerNameIndex",
          "indexes": [
            {
              "key": "customerName",
              "type": "TEXT"
            }
          ]
        }
      ]
