apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
    - name: url
      value: https://<your-cosmos-db-account>.documents.azure.com:443/
    - name: masterKey
      secretKeyRef:
        name: cosmosdb-secret
        key: masterKey
    - name: database
      value: sagaway-db
    - name: collection
      value: sagaway-state
    - name: actorStateStore
      value: "true"
auth:
  secretStore: kubernetes