# filepath: dapr/components/actorstatestore.yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: actorstatestore 
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redisserver:6379
  - name: redisPassword
    value: ""           
  - name: actorStateStore
    value: "true"