apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signalr
  template:
    metadata:
      labels:
        app: signalr
    spec:
      containers:
      - name: signalr
        image: ${ACR_NAME}.azurecr.io/signalremulator:latest
        ports:
        - containerPort: 8888
        - containerPort: 7071
        env:
        - name: ASRS_EMULATOR_PORT
          value: "8888"
        - name: ASPNETCORE_URLS
          value: "http://+:8888;http://+:7071"
---
apiVersion: v1
kind: Service
metadata:
  name: signalr
spec:
  selector:
    app: signalr
  ports:
  - name: emulator
    port: 8888
    targetPort: 8888
  - name: api
    port: 7071
    targetPort: 7071
  type: ClusterIP