name: Build and Publish All NuGet Packages

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version'
        required: false
  release:
    types: [published]

jobs:
  # Build independent packages first using a matrix
  build_independent_packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - Sagaway/Sagaway.csproj
          - Sagaway.Callback.Propagator/Sagaway.Callback.Propagator.csproj
          - Sagaway.Callback.Router/Sagaway.Callback.Router.csproj
    outputs:
      package_version: ${{ steps.get-version.outputs.package_version }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full git history for SourceLink

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Determine Package Version
      id: get-version
      run: |
        if [ "${{ github.event.release.tag_name }}" ]; then
          version="${{ github.event.release.tag_name }}"
          if [[ $version == *-* ]]; then
            echo "##[set-output name=package_version;]$version"
          else
            echo "##[set-output name=package_version;]${version##v}"
          fi
        else
          echo "##[set-output name=package_version;]${{ github.event.inputs.package_version }}"
        fi

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and Pack Independent Packages
      run: |
        dotnet pack ${{ matrix.project }} -c Release \
          -p:PackageVersion=${{ steps.get-version.outputs.package_version }} \
          -p:PackageReleaseNotes="See https://raw.githubusercontent.com/alonf/Sagaway/master/.github/README.md" \
          --include-symbols --include-source -p:SymbolPackageFormat=snupkg

    - name: Upload NuGet Package as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: independent-packages
        path: '**/*.nupkg'

  # Build dependent packages using the locally published packages
  build_dependent_packages:
    needs: build_independent_packages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full git history for SourceLink

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Download Independent Packages
      uses: actions/download-artifact@v4
      with:
        name: independent-packages

    - name: Setup Local NuGet Feed
      run: |
        mkdir -p ./local-nuget
        cp ./**/*.nupkg ./local-nuget/
        dotnet nuget add source ./local-nuget --name LocalFeed

    - name: Restore dependencies from local feed
      run: dotnet restore --source ./local-nuget

    - name: Build and Pack Dependent Packages
      run: |
        dotnet pack Sagaway.Hosts.DaprActorHost/Sagaway.Hosts.DaprActorHost.csproj -c Release \
          -p:PackageVersion=${{ needs.build_independent_packages.outputs.package_version }} \
          -p:PackageReleaseNotes="See https://raw.githubusercontent.com/alonf/Sagaway/master/.github/README.md" \
          --include-symbols --include-source -p:SymbolPackageFormat=snupkg

        dotnet pack Sagaway.OpenTelemetry/Sagaway.OpenTelemetry.csproj -c Release \
          -p:PackageVersion=${{ needs.build_independent_packages.outputs.package_version }} \
          -p:PackageReleaseNotes="See https://raw.githubusercontent.com/alonf/Sagaway/master/.github/README.md" \
          --include-symbols --include-source -p:SymbolPackageFormat=snupkg

    - name: Upload Dependent NuGet Package as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dependent-packages
        path: '**/*.nupkg'

  # Publish all packages to NuGet.org
  publish_to_nuget:
    needs: [build_independent_packages, build_dependent_packages]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download All Packages
      uses: actions/download-artifact@v4
      with:
        name: independent-packages

    - name: Download Dependent Packages
      uses: actions/download-artifact@v4
      with:
        name: dependent-packages

    - name: Publish NuGet Packages
      run: |
        dotnet nuget push '**/*.nupkg' --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json --skip-duplicate

        dotnet nuget push '**/*.snupkg' --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json --skip-duplicate
