name: Deploy AKS

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Debug Deployment Variables
        run: |
          echo "Resource Group: SagawayDemoAKS"

      - name: Deploy Infrastructure using Bicep
        run: |
          az deployment group create \
            --resource-group "SagawayDemoAKS" \
            --template-file ./aks/IaC/main.bicep
